### ISSUE TITLE
Cannot display UUID's?

### ISSUE THREAD

**Issue by mmower** [yogthos/json-html#12]
Hi.

This is a very neat library and will allow me to replace a less flexible alternative of my own. However I make a lot of use of #uuid objects (via cljs-uuid-utils) and it seems like these are tripping up the edn->hiccup converter.

I don't seem to use any special handling so I think it's just because they're not a recognised type in (render [v]) and getting rendered as a blank.

I made a quick patch adding:

(= t cljs.core/UUID) [:span.jh-type-string (str v)

and all seems well locally but I am not sure if it will work generally (i.e. without the cljs-uuid-utils library).

Perhaps there could be away to allow custom types to be rendered?

Thoughts?

m/

**Comment by yogthos** [comment]
I agree that an extension mechanism would be useful. It would probably make sense to refactor the cljs part to use a multimethod, and then you could just implement it for any custom type. If you'd be interested to take a look at doing a pr for this I can help out with that.

**Comment by mmower** [comment]
In fact when I checked I use a multi in my own implementation so that's probably a good call. I'm happy to try and come up with a patch.
