### ISSUE TITLE
sorted-map is chocking when keywords aren't of the same type

### ISSUE THREAD

**Issue by Frozenlock** [yogthos/json-html#5]
See https://github.com/yogthos/json-html/blob/master/src/json_html/core.clj#L55

I would propose to go back to the previous
`(map-indexed vector this)`

One could also stringify all keys, but the `:a` and `"a"` would collide and one of the two fields would be lost.

**Comment by yogthos** [comment]
Doing `(str :foo)` will preserve the `:`, so perhaps that would be a better way to go. I do like the predictable result of the sorted-map.

**Comment by Frozenlock** [comment]
Sounds good.

You push or I do?

**Comment by yogthos** [comment]
just made the fix :)

**Comment by yogthos** [comment]
I can push to clojars when I get home

**Comment by Frozenlock** [comment]
:heart:

**Comment by yogthos** [comment]
ok it's up on clojars, let me know if everything looks good :)

**Comment by Frozenlock** [comment]
Yup, everything works!
