### ISSUE TITLE
Problem checkin

### ISSUE THREAD

**Issue by mike-thompson-day8** [yogthos/json-html#7]
It looks to me as if this checkin was a mistake.  

https://github.com/yogthos/json-html/commit/0b9538fc433ab53bfa80f89691c4d1fb1ef0b428#diff-5d30f1b843efd4cc1c55dc2e0d11fcdaR38

First, there's a `this` used when it should be `m`.    (as a result function is broken)

Second, the introduction of `(str k)` looks wrong too (there is later a `(render k)`).  

Third, the threading seems redundant.  The original `(for [[k v] (into (sorted-map) m)]`  looks like it would have worked just fine. 

So I've begun to suspect the entire change was a mistaken checkin.

**Comment by yogthos** [comment]
Yeah `this` looks like a typo, the `(str k)` I believe was introduced to support `sorted-map` that doesn't like mixed key types.

**Comment by mike-thompson-day8** [comment]
Hmm. I can see what you mean. `sorted-map` needing consistently typed keys.  So that `(str k)` is about forcing the keys to always be str. 

But that seems a bit nasty.  I often end up with keys that are complex (when doing `group-by` for example), and forcing them to `str` seems a shame.  Does a map have to be sorted?

**Comment by yogthos** [comment]
The reason I switched to `sorted-map` is due to the fact that it gets really hard to tell if data changed when it keeps randomly shifting around with larger data structures.

One option would be to recursively walk keys until a primitive is hit and then render them out that way perhaps?

**Comment by mike-thompson-day8** [comment]
I'd suggest trying to sort, and if it fails falling back to not sorted. 

Approx:
```
[:tbody 
   (let [m'  (try 
             (into (sorted-map) m)
                (catch js/Error. e  m))]
       (for [[k v] m')
       ....
```

**Comment by yogthos** [comment]
I updated to use `sorted-map-by`:

```clojure
(sorted-map-by (fn [k1 k2] (compare (str k1) (str k2))))
```

So, the keys should be left alone now while maintaining the sort. Let me know if this looks good and I can push out a new version.

**Comment by yogthos** [comment]
actually just pushed out `0.3.3`, let me know if everything looks good to you, seems to do the right thing in my testing

**Comment by mike-thompson-day8** [comment]
I would shy away from always using a `str` based solution as the default.  To me, using `str` should be the throw-your-hands-in-the-air fallback position (which needs to be used rarely).

I get that, in this case, the sorting is about "consistent ordering" more than "real ordering", but it bugs me that `str` version of numbers would lead to the key  "111" appearing before "2".  

So my version would be:  
```
[:tbody 
   (let [m' (try 
              (into (sorted-map) m)              ;; 
              (catch js/Error. e  XXXX))]       ;;  <--   fall back to str based sorting in here
       (for [[k v] m')
       ....
```

**Comment by yogthos** [comment]
Sure, that seems reasonable to me.

**Comment by yogthos** [comment]
I made the change, if you can try it locally and confirm that it works as expected then I can push it out

**Comment by yogthos** [comment]
ok I released the update that attempts to use a sorted-map as the default comparitor, I think it's safe to close this one

**Comment by mike-thompson-day8** [comment]
Looking good.  Many Thanks!

**Comment by yogthos** [comment]
:+1:
